In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score,recall_score,f1_score

In [2]:
df=pd.read_csv('data/student_lifestyle_100k.csv')
df=df.drop('Student_ID',axis=1)
df.head()

,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression
0,22,Female,Science,3.50,7.3,3.3,3.4,114,5,False
1,20,Male,Engineering,2.72,5.5,7.2,6.0,142,2,False
2,20,Male,Medical,3.01,5.4,2.3,1.8,137,3,False
3,21,Male,Engineering,3.63,8.1,2.0,4.6,130,3,False
4,19,Male,Arts,3.14,6.8,2.6,4.3,4,6,False

In [3]:
df=pd.get_dummies(df,columns=["Gender","Department"],drop_first=True)

In [4]:
df.head()

,Age,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression,Gender_Male,Department_Business,Department_Engineering,Department_Medical,Department_Science
0,22,3.50,7.3,3.3,3.4,114,5,False,False,False,False,False,True
1,20,2.72,5.5,7.2,6.0,142,2,False,True,False,True,False,False
2,20,3.01,5.4,2.3,1.8,137,3,False,True,False,False,True,False
3,21,3.63,8.1,2.0,4.6,130,3,False,True,False,True,False,False
4,19,3.14,6.8,2.6,4.3,4,6,False,True,False,False,False,False

In [5]:
df.shape

(100000, 13)

In [6]:
y=df['Depression']
x=df.drop('Depression',axis=1)

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.9,random_state=42)

In [8]:
rf=RandomForestClassifier()
model=rf.fit(x_train,y_train)

In [9]:
model.score(x_test,y_test)

0.9001

In [10]:
df['Depression'].value_counts()

Depression
False    89938
True     10062
Name: count, dtype: int64

In [11]:
sonuc=model.predict(x_test)
dfs=pd.DataFrame()
dfs['sonuc']=sonuc
dfs['gercek']=y_test.values
dfs['sonuc'].value_counts()

sonuc
False    9950
True       50
Name: count, dtype: int64

In [12]:
dfs['gercek'].value_counts()

gercek
False    9009
True      991
Name: count, dtype: int64

In [13]:
dfs['truebil']=(dfs['gercek']==True) & (dfs['sonuc']==True)

In [14]:
dfs['truebil'].value_counts()

truebil
False    9979
True       21
Name: count, dtype: int64

In [15]:
17/47

0.3617021276595745

In [16]:
precision=precision_score(dfs['gercek'],dfs['sonuc'])

In [17]:
17/991

0.017154389505549948

In [18]:
recall=recall_score(dfs['gercek'],dfs['sonuc'])

In [19]:
2*(precision*recall)/(precision+recall)

0.040345821325648415

In [20]:
f1_score(dfs['gercek'],dfs['sonuc'])

0.040345821325648415